/* tslint:disable */
/* eslint-disable */
/**
 * Today\'s Wildlife API
 * API for Today\'s Wildlife application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WildlifeInfo
 */
export interface WildlifeInfo {
    /**
     * 
     * @type {string}
     * @memberof WildlifeInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof WildlifeInfo
     */
    'habitat': string;
    /**
     * 
     * @type {string}
     * @memberof WildlifeInfo
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof WildlifeInfo
     */
    'tips': string;
    /**
     * 
     * @type {string}
     * @memberof WildlifeInfo
     */
    'createdAt': string;
}

