steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - update-wildlife-info-function
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=./spino-batch
      - --entry-point=updateWildlifeInfo
      - --trigger-topic=update-wildlife-info
      - --set-env-vars
      - COLLECTION_NAME=WildlifeInfo
